# Generated by Django 3.1.5 on 2021-01-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес проживания')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('password', models.CharField(max_length=128, verbose_name='Хэш пароля')),
                ('token', models.CharField(editable=False, max_length=10, verbose_name='Токен')),
            ],
        ),
    ]
