# Generated by Django 3.1.5 on 2021-01-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Гражданин', 'verbose_name_plural': 'Граждане'},
        ),
    ]
